apiVersion: gateway-operator.konghq.com/v2beta1
kind: GatewayConfiguration

metadata:
  name: kong-configuration
  namespace: kong

spec:
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
            - name: proxy
              image: mayess03/kong-gateway-moesif:3.9
              env:
                - name: KONG_PLUGINS
                  value: "bundled,moesif"