FROM wso2/wso2am-acp:4.7.0

ADD --chown=wso2carbon:wso2 \
  https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar \
  /home/wso2carbon/wso2am-acp-4.7.0/repository/components/lib/